#!/usr/bin/env bash
# using sed to redirect 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="sever_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/Reem-degais permanent;"

sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
