#!/usr/bin/env bash
# using sed to redirect 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/Reem-degais permanent;"
bash -c "echo -e '$string_for_replacement'" > /etc/nginx/sites-enabled/default
sudo service nginx restart
