#!/usr/bin/env bash
# Install Nginx with server 0x01 config
#+ add HTTP header named X-Served-By $HOSTNAME

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" | sudo tee  /var/www/html/404.html
sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=xJJsoquu70o/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
