#!/usr/bin/env bash
# A Bash script that configures the Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
SE="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
        try_files $uri $uri/ =404;
        }
}"

sudo bash -c "echo -e '$SE'" | sudo tee /etc/nginx/sites-enabled/default

sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;location = /custom_404.html {root /usr/share/nginx/html;internal;}" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx reload
