#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install haproxy=2.0.\*

sudo echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 3.94.185.152:80 check
        server web2 34.207.155.69:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
