#!/usr/bin/env bash
#configuration file for the local SSH client to
#connect to a server without typing a password
SendEnv LANG LC_*
IdentityFile ~/.ssh/school
PasswordAuthentication no
HashKnownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredentials no
